[default.variables]
# Theme: onedarkpro-darker
bg_primary = "#0c0e15"
bg_secondary = "#1e2127"
bg_tertiary = "#282c34"
fg_primary = "#a7aebe"
fg_secondary = "#8a909e"
fg_tertiary = "#5c6370"
accent_blue = "#61afef"
accent_green = "#98c379"
accent_red = "#e06c75"
accent_yellow = "#e5c07b"
accent_orange = "#d19a66"
accent_purple = "#c678dd"
accent_pink = "#e06c75"
accent_cyan = "#56b6c2"
success = "#98c379"
warning = "#e5c07b"
error = "#e06c75"
info = "#61afef"
border_active = "#61afef"
border_inactive = "#282c34"
shadow = "#0a0c12"
# Hyprland specific (without #)
hypr_border_active = "61afef"
hypr_border_inactive = "282c34"
hypr_shadow = "0a0c12ee"