[default.variables]
# Global color scheme variables (OneDarkPro theme)
bg_primary = "#0C0E15"
bg_secondary = "#1E2127"
bg_tertiary = "#282C34"
fg_primary = "#A7AEBE"
fg_secondary = "#8A909E"
fg_tertiary = "#5C6370"
accent_blue = "#61AFEF"
accent_green = "#98C379"
accent_red = "#E06C75"
accent_yellow = "#E5C07B"
accent_orange = "#D19A66"
accent_purple = "#C678DD"
accent_pink = "#E06C75"
accent_cyan = "#56B6C2"
success = "#98C379"
warning = "#E5C07B"
error = "#E06C75"
info = "#61AFEF"
border_active = "#61AFEF"
border_inactive = "#282C34"
border_default = "#282C34"
shadow = "#0a0c12"
hover = "#282C34"
accent_alt = "#4a90e2"
fg_disabled = "#5C6370"
# Hyprland specific (without #)
hypr_border_active = "61AFEF"
hypr_border_inactive = "282C34"
hypr_shadow = "0A0C12EE"