# Bottom (btm) configuration
# System monitor similar to top/htop but with more features

[flags]
# Whether to hide the average cpu entry
hide_avg_cpu = false

# Whether to use dot markers rather than braille
dot_marker = false

# The update rate of the application
rate = "1s"

# Whether to put the CPU legend to the left
cpu_left_legend = false

# Whether to set CPU% on a process to be based on the total CPU or just current usage
current_usage = false

# Whether to group processes with the same name together by default
group_processes = false

# Whether to make process searching case sensitive by default
case_sensitive = false

# Whether to make process searching look for matching the entire word by default
whole_word = false

# Whether to make process searching use regex by default
regex = false

# The temperature unit. One of: "c", "f", "k", "celsius", "fahrenheit", "kelvin"
temperature_type = "c"

# The default time interval
default_time_value = "60s"

# The time delta on each zoom in/out action (in milliseconds)
time_delta = 15000

# Hides the time scale
hide_time = false

# Use basic mode
basic = false

# Use the old network legend style
use_old_network_legend = false

# Remove space in tables
hide_table_gap = false

# Show the battery widgets
battery = true

# Disable mouse clicks
disable_click = false

# Show memory values in the processes widget as values by default
process_memory_as_value = false

# Show tree mode by default in the processes widget
tree = false

# Shows an indicator in table widgets tracking where in the list you are
show_table_scroll_position = false

# Show processes as their commands by default in the process widget
process_command = false

# Displays the network widget with binary prefixes
network_use_binary_prefix = false

# Displays the network widget using bytes
network_use_bytes = false

# Displays the network widget with a log scale
network_use_log = false

# Hides advanced options to stop a process on Unix-like systems
disable_advanced_kill = false

# Hide GPU(s) information
disable_gpu = false

# Shows cache and buffer memory
enable_cache_memory = true

# How much data is stored at once in terms of time
retention = "10m"

# Where to place the legend for the memory widget
memory_legend = "top-right"

# Where to place the legend for the network widget
network_legend = "top-right"

# Processes widget configuration
[processes]
# The columns shown by the process widget
columns = ["PID", "User", "Name", "CPU%", "Mem%", "State"]

# CPU widget configuration
[cpu]
# One of "all" (default), "average"/"avg"
default = "all"

# Disk widget configuration
[disk]
# The columns shown by the disk widget
columns = ["Disk", "Mount"]

# Custom styling - matching OneDarkPro theme
[styles]
# Use a custom color scheme instead of built-in themes
theme = "default"

[styles.cpu]
all_entry_color = "{{accent_blue}}"
avg_entry_color = "{{accent_green}}"
cpu_core_colors = [
    "{{accent_purple}}",
    "{{accent_yellow}}",
    "{{accent_cyan}}",
    "{{accent_green}}",
    "{{accent_blue}}",
    "{{accent_orange}}",
    "{{accent_red}}",
    "{{accent_pink}}",
]

[styles.memory]
ram_color = "{{accent_purple}}"
cache_color = "{{accent_orange}}"
swap_color = "{{accent_yellow}}"
arc_color = "{{accent_cyan}}"

[styles.network]
rx_color = "{{accent_purple}}"
tx_color = "{{accent_yellow}}"
rx_total_color = "{{accent_cyan}}"
tx_total_color = "{{accent_green}}"

[styles.battery]
high_battery_color = "{{success}}"
medium_battery_color = "{{warning}}"
low_battery_color = "{{error}}"

[styles.tables]
headers = { color = "{{accent_blue}}", bold = true }

[styles.graphs]
graph_color = "{{fg_secondary}}"
legend_text = { color = "{{fg_secondary}}" }

[styles.widgets]
border_color = "{{fg_tertiary}}"
selected_border_color = "{{border_active}}"
widget_title = { color = "{{fg_primary}}" }
text = { color = "{{fg_primary}}" }
selected_text = { color = "{{bg_primary}}", bg_color = "{{accent_blue}}" }
disabled_text = { color = "{{fg_disabled}}" }

# Custom layout - organized for better space utilization
[[row]]
ratio = 30
[[row.child]]
ratio = 2
type = "cpu"
[[row.child]]
[[row.child.child]]
type = "net"
[[row.child.child]]
type = "mem"

[[row]]
ratio = 40
[[row.child]]
ratio = 2
type = "proc"
default = true
[[row.child]]
[[row.child.child]]
type = "temp"
[[row.child.child]]
type = "disk"
