#External Dependencies
[zsh.variables.dependencies.zsh-completions]
type = "git"
url = "https://github.com/zsh-users/zsh-completions.git"
path = "zsh/zsh-completions"
description = "Additional completion definitions for Zsh"

[zsh.variables.dependencies.zsh-syntax-highlighting]
type = "git"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
path = "zsh/zsh-syntax-highlighting"
description = "Fish shell like syntax highlighting for Zsh"

[zsh.variables.dependencies.zsh-autosuggestions]
type = "git"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
path = "zsh/zsh-autosuggestions"
description = "Fish-like autosuggestions for Zsh"

[nvim.variables.dependencies.lazy]
type = "git"
url = "https://github.com/folke/lazy.nvim.git"
path = "nvim/lazy"
branch = "stable"
description = "A modern plugin manager for Neovim"
